name: Nextcicd

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Generate deployment package
        run: zip -r app2.zip .platform .next pages public styles *.json
 
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'next-test'
          environment_name: 'alpha-next-test'
          version_label: ${{github.sha}}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
