name: Nextcicd

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "NEXT_PUBLIC_ENVIRONMENT=alpha" >> $GITHUB_ENV
            echo "ENVIRONMENT_NAME=savenote-fe-alpha" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "NEXT_PUBLIC_ENVIRONMENT=production" >> $GITHUB_ENV
            echo "ENVIRONMENT_NAME=savenote-fe-production" >> $GITHUB_ENV
          fi

      - name: Install Dependencies
        run: npm install

      - name: Build the Next.js app
        run: npm run build

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.0
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Generate deployment package
        run: zip -r deploy.zip .platform .next pages public styles *.json

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "savenote-fe"
          environment_name: ${{ env.ENVIRONMENT_NAME }}
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
