name: Nextcicd

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {
              branch: "develop",
              environment_name: "savenote-fe-alpha",
              next_public_env: "alpha",
            }
          - {
              branch: "main",
              environment_name: "savenote-fe-production",
              next_public_env: "production",
            }

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set Environment Variables
        run: echo "NEXT_PUBLIC_ENVIRONMENT=${{ matrix.env.next_public_env }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Build the Next.js app
        run: npm run build

      - name: Generate deployment package
        run: zip -r deploy.zip .platform .next pages public styles *.json

      - name: Beanstalk Deploy
        if: github.ref == 'refs/heads/${{ matrix.env.branch }}'
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "savenote-fe"
          environment_name: ${{ matrix.env.environment_name }}
          version_label: ${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
