name: Nextcicd

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set Environment Variables
        if: github.ref == 'refs/heads/develop'
        run: echo "NEXT_PUBLIC_ENVIRONMENT=alpha" >> $GITHUB_ENV

      - name: Set Environment Variables
        if: github.ref == 'refs/heads/main'
        run: echo "NEXT_PUBLIC_ENVIRONMENT=production" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Build the Next.js app
        run: npm run build

      - name: Generate deployment package
        run: zip -r deploy.zip .platform .next pages public styles *.json

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'kb-fe'
          environment_name: 'alpha'
          version_label: ${{github.sha}}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
